Repository golemfactory/golem-electron, pull requests merged in 2018-10, with the labels that each got.

#446 remove the `concent_enabled: false` setting from `comp.task.create` a…
  src/components/tasks/TaskDetail.js
Labels: bug :beetle:

#396 Raw data on connection status
  .gitignore
  src/sagas/index.js
Labels: _current :watch:

#418 Test result RPC changes
  src/components/tasks/TaskDetail.js
  src/sagas/handler.js
  src/sagas/tasks.js
Labels: in progress :hourglass_flowing_sand:

#442 Disable withdraw if there's no fund available in wallet
  src/components/wallet/CurrencyBox.js
  src/components/wallet/index.js
Labels: _current :watch:

#444 Custom Flags
  README.md
  electron/golem_config.js
  electron/golem_handler.js
  index.js
  package-lock.json
  package.json
  src/sagas/handler.js
Labels: _current :watch:

#443 Multiple file option implementation
  index.js
  setup_jest.js
  src/assets/fonts/Gcon/gcon.eot
  src/assets/fonts/Gcon/gcon.svg
  src/assets/fonts/Gcon/gcon.ttf
  src/assets/fonts/Gcon/gcon.woff
  src/components/Dropzone.js
  src/components/Header.js
  src/scss/header.scss
Labels: _current :watch:, to be merged 🔜

#449 Win connecting network issue fix
  package-lock.json
  package.json
  setup_jest.js
  src/actions/index.js
  src/components/Dropzone.js
  src/components/FooterMain.js
  src/components/__tests__/network/index.test.js
  src/components/network/index.js
  src/components/network/tabs/Advanced.js
  src/components/network/tabs/History.js
  src/components/tasks/TaskDetail.js
  src/components/tasks/index.js
  src/container/App.js
  src/container/modal/PasswordModal.js
  src/reducers/__tests__/real-time.test.js
  src/reducers/index.js
  src/reducers/network/history.js
  src/reducers/realTime.js
  src/reducers/settings/performance.js
  src/sagas/__tests__/index.test.js
  src/sagas/engine.js
  src/sagas/golem.js
  src/sagas/handler.js
  src/sagas/index.js
  src/sagas/performance.js
  src/scss/network/tabs/advanced.scss
Labels: _current :watch:

#450 File/folder upload option style fixed
  src/components/Header.js
  src/scss/header.scss
Labels: _current :watch:

#451 Old presets empty format issue fixed
  src/components/tasks/TaskDetail.js
Labels: _current :watch:

#454 Wampcra initial start issue
  electron/golem_handler.js
  src/sagas/index.js
Labels: _current :watch:

#455 Linux Hardware Acceleration disabled
  index.js
  src/reducers/settings/performance.js
Labels: _current :watch:

#456 Arguemnt parser changed as yargs
  electron/golem_config.js
  package-lock.json
  package.json
Labels: _current :watch:

#459 React virtualized implemented to solve history list performance issue
  index.js
  package-lock.json
  package.json
  setup_jest.js
  src/components/network/tabs/History.js
  src/scss/network/index.scss
  src/scss/network/tabs/history.scss
Labels: _current :watch:

#458 React motion animation library replaced with react-spring
  circle.yml
  index.js
  package-lock.json
  package.json
  setup_jest.js
  src/components/SpotLight.js
  src/components/__tests__/__snapshots__/loader.test.js.snap
  src/components/__tests__/loader.test.js
  src/components/hoc/Loader.js
  src/components/hoc/Onboarding.js
  src/components/network/Indicator.js
  src/components/network/tabs/History.js
  src/components/tasks/Table.js
  src/components/tasks/TaskItem.js
  src/components/tasks/frame/All.js
  src/components/wallet/CurrencyBox.js
  src/components/wallet/index.js
  src/reducers/network/history.js
  src/scss/network/index.scss
  src/scss/network/tabs/history.scss
Labels: _current :watch:

#460 Initial certificate creation fix
  electron/golem_handler.js
Labels: _current :watch:

#461 Defautl input value
  src/components/wallet/modal/WithdrawModal.js
Labels: _current :watch:

#462 Applying default file preset fix
  src/components/tasks/TaskDetail.js
Labels: _current :watch:

#465 Hang on "Connecting network" issue fix
  src/sagas/connectedPeers.js
Labels: _current :watch:

#466 HW active preset issue fix
  src/components/tasks/index.js
Labels: _current :watch:
