Repository golemfactory/golem-electron, pull requests merged in 2018-03, with the labels that each got.

#216 Custom Geth options added to settings tab
  electron/config_storage.js
  electron/golem_handler.js
  electron/menu_handler.js
  src/actions/index.js
  src/components/settings/Geth.js
  src/components/settings/index.js
  src/reducers/index.js
  src/reducers/settings/geth.js
  src/scss/main.scss
  src/scss/settings/file-location.scss
  src/scss/settings/geth.scss
  src/scss/settings/index.scss
Labels: in progress

#231 Structure supply
  .babelrc
  index.js
  package.json
  server.js
  setup_golem.js
  src/components/Dropzone.js
  src/components/Header.js
  src/components/settings/FileLocation.js
  src/components/tasks/frame/SubTask.js
  webpack.config.babel.js
  webpack.config.prod.babel.js
  yarn.lock
Labels: in progress

#255 Secure WebSockets, certificate trust and recent datadir changes
  electron/debug_handler.js
  electron/golem_config.js
  electron/golem_handler.js
  src/sagas/handler.js
Labels: needs review

#241 Rpc pass
  electron/config_storage.js
  index.js
  package.json
  src/actions/index.js
  src/assets/img/locked.svg
  src/assets/img/main-net-icon.svg
  src/assets/img/oh-really.svg
  src/assets/img/pen.svg
  src/assets/img/print.svg
  src/assets/img/terms.svg
  src/assets/img/test-net-icon.svg
  src/assets/img/unlocked.svg
  src/components/onboarding/index.js
  src/components/onboarding/steps/ChainInfo.js
  src/components/onboarding/steps/Decline.js
  src/components/onboarding/steps/Print.js
  src/components/onboarding/steps/Register.js
  src/components/onboarding/steps/Terms.js
  src/components/onboarding/steps/Type.js
  src/components/onboarding/steps/Welcome.js
  src/components/tasks/NewTask.js
  src/container/App.js
  src/container/__tests__/app.test.js
  src/container/modal/PasswordModal.js
  src/reducers/__tests__/real-time.test.js
  src/reducers/info.js
  src/reducers/realTime.js
  src/sagas/__tests__/index.test.js
  src/sagas/golem.js
  src/sagas/handler.js
  src/sagas/index.js
  src/sagas/password.js
  src/sagas/terms.js
  src/sagas/userSettings.js
  src/scss/main.scss
  src/scss/onboarding/index.scss
  src/scss/onboarding/steps/terms.scss
  src/scss/password-modal.scss
  yarn.lock
Labels: in progress, to be merged
